gen_key=🔐 Generando nueva clave simétrica...
key_created=✅ Clave creada en {path}
rotate_start=🔄 Rotando clave y re-cifrando secretos...
recrypt=🔁 Re-cifrando '{key}'...
rotate_done=✅ Rotación completada. Clave antigua guardada en {path}
status_title=📊 Estado del Vault
sym_key=🔐 Clave simétrica: {status}
pub_key=🔐 Clave pública: {status}
present=✅ presente
absent=❌ ausente
vault_path=📁 Ruta del vault: {path}
secrets=📦 Secretos: {count}
last_mod=🕒 Última modificación: {date}
asym_start=🔐 Configurando cifrado asimétrico...
asym_hint=⚠️ Se requiere que la clave pública esté exportada previamente.
pubkey_found=✅ Clave pública detectada en {path}
pubkey_missing=❌ Clave pública no encontrada. Exporta primero con GPG.
no_key=❌ No existe clave actual. Ejecuta sin --rotate primero.
key_exists=🔐 Clave ya existe en {path}
