missing_convert=❌ [openssl] Faltan argumentos para conversión: src, dest, format
missing_inspect=❌ [openssl] Archivo no encontrado para inspección: {src}
missing_trust=❌ [openssl] Faltan argumentos para instalación como CA: src, alias, trust_path
missing_untrust=❌ [openssl] Faltan argumentos para eliminación: alias, trust_path
src_not_found=❌ [openssl] Archivo no encontrado: {src}
converting=🔐 [openssl] Convirtiendo {src} a formato {format}...
converted=✅ [openssl] Conversión completada: {dest}
key_extracted=✅ [openssl] Clave extraída: {dest}
cer_converted=✅ [openssl] Certificado convertido a .cer: {dest}
unsupported_format=❌ [openssl] Formato de destino no soportado: {format}
inspecting=🔍 [openssl] Inspeccionando certificado: {src}
inspect_fail=⚠️ [openssl] No se pudo extraer información
trusting=🏛️ [openssl] Instalando certificado '{alias}' como CA...
trusted=✅ [openssl] Certificado instalado y CA actualizada
untrust_not_found=⚠️ [openssl] Certificado '{alias}' no encontrado en {trust_path}
untrusting=🧹 [openssl] Eliminando certificado '{alias}' de CA confiables...
untrusted=✅ [openssl] Certificado eliminado y CA actualizada
unknown_state=❌ [openssl] Estado desconocido: '{state}'. Usa 'convert', 'inspect', 'trust' o 'untrust'
missing_deps=❌ [openssl] Dependencias faltantes: {cmds}
deps_ok=✅ [openssl] Todas las dependencias están disponibles
