missing_args=❌ [smtp_send] Faltan argumentos obligatorios: smtp_server, smtp_user, smtp_pass, from, to
start=📡 [smtp_send] Preparando envío a {to} vía {server}:{port}...
using_nc=🔧 Usando netcat para conexión SMTP...
using_openssl=🔧 Usando openssl para conexión STARTTLS...
missing_tools=❌ [smtp_send] No se encontró ni netcat (nc) ni openssl en el sistema.
missing_base64=❌ [smtp_send] Falta base64 en el sistema.
deps_ok=✅ [smtp_send] Herramientas disponibles: {tool}, base64
done=✅ [smtp_send] Comando ejecutado. Verifica si el correo fue recibido.
